name: bot-v3-scan-min

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * 1-5'  # every 15 min (we'll switch to 5 after it works)

jobs:
  scan:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scanner
        run: |
          echo "Hello from Actions. Running Python…"
          python - << 'PY'
print("Python OK")
PY

      - name: Commit CSV if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update trades_log_v3_min.csv'
          file_pattern: 'trades_log_v3_min.csv'
